title: ""
description: "PÃ¡gina creada con Jekyll y GitHub Pages"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

header_pages:
  - index.md
  - about.md
  - contact.md
